Update keepalived

diff --git a/jobs/vip/templates/bin/keepalived b/jobs/vip/templates/bin/keepalived
--- a/jobs/vip/templates/bin/keepalived
+++ b/jobs/vip/templates/bin/keepalived
@@ -78,46 +78,38 @@ case $1 in
     mkdir -p $RUN_DIR $LOG_DIR
     chown -R vcap:vcap $RUN_DIR $LOG_DIR
 
-    <% if p("keepalived.enabled") == "true" -%>
-        <% if p("keepalived.interface") == "auto" -%>
-        interface=$(interface_for_ip <%= p("vip") %>)
-        if [[ $? != 0 || -z ${interface} ]]; then
-            echo "Could not autodetect interface to use for <%= p("vip") %>. Cannot continue."
-            exit 1
-        fi
-        if grep "interface auto" ${CONF_DIR}/keepalived.tpl > /dev/null; then
-            sed "s/interface auto/interface ${interface}/" ${CONF_DIR}/keepalived.tpl > ${CONF_DIR}/keepalived.conf
-        fi
-        <% else -%>
-        cp ${CONF_DIR}/keepalived.tpl ${CONF_DIR}/keepalived.conf
-        <% end -%>
-
-        $SBIN_DIR/keepalived -l -D -n \
-            -f $CONF_DIR/keepalived.conf \
-            --pid=$RUN_DIR/keepalived.pid \
-            --vrrp_pid=${RUN_DIR}/vrrp.pid \
-            --checkers_pid=${RUN_DIR}/checkers.pid \
+    <% if p("keepalived.interface") == "auto" -%>
+    interface=$(interface_for_ip <%= p("vip") %>)
+    if [[ $? != 0 || -z ${interface} ]]; then
+        echo "Could not autodetect interface to use for <%= p("vip") %>. Cannot continue."
+        exit 1
+    fi
+    if grep "interface auto" ${CONF_DIR}/keepalived.tpl > /dev/null; then
+        sed "s/interface auto/interface ${interface}/" ${CONF_DIR}/keepalived.tpl > ${CONF_DIR}/keepalived.conf
+    fi
     <% else -%>
-        echo "1" > $RUN_DIR/keepalived.pid
+    cp ${CONF_DIR}/keepalived.tpl ${CONF_DIR}/keepalived.conf
     <% end -%>
+
+    $SBIN_DIR/keepalived -l -D -n \
+        -f $CONF_DIR/keepalived.conf \
+        --pid=$RUN_DIR/keepalived.pid \
+        --vrrp_pid=${RUN_DIR}/vrrp.pid \
+        --checkers_pid=${RUN_DIR}/checkers.pid \
     ;;
 
   stop)
     echo "Stopping keepalived... ($(date))"
-    <% if p("keepalived.enabled") == "true" -%>
-        for PIDFILE in ${RUN_DIR}/*.pid; do
-            pid=$(cat $PIDFILE)
-            [[ -z "${pid}" ]] && continue
-            kill "${pid}"
-            wait_pid_death "${pid}" 25
-            if pid_is_running "${pid}"; then
-                kill -9 ${pid}
-            fi
-            rm -f $PIDFILE
-        done
-    <% else -%>
+    for PIDFILE in ${RUN_DIR}/*.pid; do
+        pid=$(cat $PIDFILE)
+        [[ -z "${pid}" ]] && continue
+        kill "${pid}"
+        wait_pid_death "${pid}" 25
+        if pid_is_running "${pid}"; then
+            kill -9 ${pid}
+        fi
         rm -f $PIDFILE
-    <% end -%>
+    done
 
     ;;
 
